create extension if not exists pgcrypto;

create table if not exists public.goals (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade,
  title text not null, status text not null default 'active' check (status in ('active','completed','paused')),
  target_date timestamptz, created_at timestamptz not null default now()
);
create table if not exists public.actions (
  id uuid primary key default gen_random_uuid(), goal_id uuid not null references public.goals(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade, title text not null,
  status text not null default 'todo' check (status in ('todo','done','skipped')),
  estimate_minutes int, sort_order int not null default 0, completed_at timestamptz, created_at timestamptz not null default now()
);
create table if not exists public.wins (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade,
  goal_id uuid references public.goals(id) on delete set null, title text not null, summary text, created_at timestamptz not null default now()
);
create table if not exists public.events (
  id bigint generated by default as identity primary key, user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null, object_id text, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now()
);

alter table public.goals enable row level security; alter table public.actions enable row level security; alter table public.wins enable row level security; alter table public.events enable row level security;

do $$ begin
  create policy "users own goals" on public.goals for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "users own actions" on public.actions for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "users own wins" on public.wins for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "users own events" on public.events for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
exception when duplicate_object then null; end $$;
