import { useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { supabase } from '@/lib/supabase';

function draftActions(title:string){const t=title.toLowerCase(); if(t.includes('run')||t.includes('5k'))return [['Choose a day and route',10],['Complete an easy training session',30],['Do the planned run',45]]; if(t.includes('clean')||t.includes('garage'))return [['Pick one small zone',5],['Clear trash and donations',20],['Organize what stays',30]]; if(t.includes('cake'))return [['Choose the cake',10],['Get ingredients',25],['Bake and decorate',90]]; return [['Define what done looks like',10],['Do the smallest useful first move',20],['Complete the next meaningful step',30]] as [string,number][];}
export default function GoalIt(){const[title,setTitle]=useState(''),[saving,setSaving]=useState(false); async function create(){if(!title.trim())return;setSaving(true);const{data:{user}}=await supabase.auth.getUser();if(!user)return;const{data:goal,error}=await supabase.from('goals').insert({user_id:user.id,title:title.trim(),status:'active'}).select().single();if(error||!goal){Alert.alert('Could not create goal',error?.message);setSaving(false);return;}const acts=draftActions(title).map(([name,min],i)=>({user_id:user.id,goal_id:goal.id,title:name,status:'todo',estimate_minutes:min,sort_order:i}));await supabase.from('actions').insert(acts);await supabase.from('events').insert({user_id:user.id,event_type:'goal_created',object_id:goal.id,metadata:{title:title.trim()}});router.replace('/today');}
return <View style={s.page}><Text style={s.brand}>GOAL IT</Text><Text style={s.h1}>What do you want to get done?</Text><Text style={s.copy}>Big or small. GOAL'D IN will turn it into moves you can actually take.</Text><TextInput value={title} onChangeText={setTitle} autoFocus multiline placeholder="Build a fire pit... Run my first 5K... Clean the garage..." placeholderTextColor="#666" style={s.input}/><Pressable onPress={create} disabled={saving} style={s.button}><Text style={s.buttonText}>{saving?'BUILDING...':'BUILD MY PLAN →'}</Text></Pressable><Pressable onPress={()=>router.back()}><Text style={s.cancel}>Cancel</Text></Pressable></View>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#090909',padding:24,paddingTop:70},brand:{color:'#D8B24A',fontWeight:'900',letterSpacing:3},h1:{fontSize:38,lineHeight:41,color:'#fff',fontWeight:'900',marginTop:16},copy:{color:'#999',fontSize:16,lineHeight:23,marginVertical:20},input:{minHeight:150,backgroundColor:'#171717',borderRadius:18,borderWidth:1,borderColor:'#2a2a2a',color:'#fff',fontSize:20,padding:18,textAlignVertical:'top'},button:{backgroundColor:'#D8B24A',padding:17,borderRadius:15,alignItems:'center',marginTop:14},buttonText:{fontWeight:'900',color:'#090909'},cancel:{color:'#777',textAlign:'center',marginTop:18}});
